# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/grpc_proto/example_proto_by_option/other/other.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n<example/grpc_proto/example_proto_by_option/other/other.proto\x12\x16other_social_by_option\x1a\x1bgoogle/protobuf/empty.proto\x1a;example/grpc_proto/example_proto_by_option/common/api.proto"#\n\x0b\x44\x65moMessage\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\t"T\n\x16SubSubSubNestedMessage\x12:\n\rrepeated_demo\x18\x01 \x03(\x0b\x32#.other_social_by_option.DemoMessage"\xc1\x01\n\x13SubSubNestedMessage\x12J\n\x08map_demo\x18\x01 \x03(\x0b\x32\x38.other_social_by_option.SubSubNestedMessage.MapDemoEntry\x1a^\n\x0cMapDemoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12=\n\x05value\x18\x02 \x01(\x0b\x32..other_social_by_option.SubSubSubNestedMessage:\x02\x38\x01"V\n\x10SubNestedMessage\x12\x42\n\rrepeated_demo\x18\x01 \x03(\x0b\x32+.other_social_by_option.SubSubNestedMessage"\xaf\x01\n\rNestedMessage\x12\x44\n\x08map_demo\x18\x01 \x03(\x0b\x32\x32.other_social_by_option.NestedMessage.MapDemoEntry\x1aX\n\x0cMapDemoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.other_social_by_option.SubNestedMessage:\x02\x38\x01\x32\xb5\x01\n\x05Other\x12\xab\x01\n\x0bnested_demo\x12\x16.google.protobuf.Empty\x1a%.other_social_by_option.NestedMessage"]\x8a\xd3\xe4\x93\x02W"\x14\n\x12/other/nested-demo\xe2\x01>\x12</map_demo/${}/repeated_demo/$[]/$.map_demo/${}/repeated_demob\x06proto3'
)


_DEMOMESSAGE = DESCRIPTOR.message_types_by_name["DemoMessage"]
_SUBSUBSUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name["SubSubSubNestedMessage"]
_SUBSUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name["SubSubNestedMessage"]
_SUBSUBNESTEDMESSAGE_MAPDEMOENTRY = _SUBSUBNESTEDMESSAGE.nested_types_by_name["MapDemoEntry"]
_SUBNESTEDMESSAGE = DESCRIPTOR.message_types_by_name["SubNestedMessage"]
_NESTEDMESSAGE = DESCRIPTOR.message_types_by_name["NestedMessage"]
_NESTEDMESSAGE_MAPDEMOENTRY = _NESTEDMESSAGE.nested_types_by_name["MapDemoEntry"]
DemoMessage = _reflection.GeneratedProtocolMessageType(
    "DemoMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _DEMOMESSAGE,
        "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
        # @@protoc_insertion_point(class_scope:other_social_by_option.DemoMessage)
    },
)
_sym_db.RegisterMessage(DemoMessage)

SubSubSubNestedMessage = _reflection.GeneratedProtocolMessageType(
    "SubSubSubNestedMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SUBSUBSUBNESTEDMESSAGE,
        "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
        # @@protoc_insertion_point(class_scope:other_social_by_option.SubSubSubNestedMessage)
    },
)
_sym_db.RegisterMessage(SubSubSubNestedMessage)

SubSubNestedMessage = _reflection.GeneratedProtocolMessageType(
    "SubSubNestedMessage",
    (_message.Message,),
    {
        "MapDemoEntry": _reflection.GeneratedProtocolMessageType(
            "MapDemoEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY,
                "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
                # @@protoc_insertion_point(class_scope:other_social_by_option.SubSubNestedMessage.MapDemoEntry)
            },
        ),
        "DESCRIPTOR": _SUBSUBNESTEDMESSAGE,
        "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
        # @@protoc_insertion_point(class_scope:other_social_by_option.SubSubNestedMessage)
    },
)
_sym_db.RegisterMessage(SubSubNestedMessage)
_sym_db.RegisterMessage(SubSubNestedMessage.MapDemoEntry)

SubNestedMessage = _reflection.GeneratedProtocolMessageType(
    "SubNestedMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SUBNESTEDMESSAGE,
        "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
        # @@protoc_insertion_point(class_scope:other_social_by_option.SubNestedMessage)
    },
)
_sym_db.RegisterMessage(SubNestedMessage)

NestedMessage = _reflection.GeneratedProtocolMessageType(
    "NestedMessage",
    (_message.Message,),
    {
        "MapDemoEntry": _reflection.GeneratedProtocolMessageType(
            "MapDemoEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _NESTEDMESSAGE_MAPDEMOENTRY,
                "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
                # @@protoc_insertion_point(class_scope:other_social_by_option.NestedMessage.MapDemoEntry)
            },
        ),
        "DESCRIPTOR": _NESTEDMESSAGE,
        "__module__": "example.grpc_proto.example_proto_by_option.other.other_pb2"
        # @@protoc_insertion_point(class_scope:other_social_by_option.NestedMessage)
    },
)
_sym_db.RegisterMessage(NestedMessage)
_sym_db.RegisterMessage(NestedMessage.MapDemoEntry)

_OTHER = DESCRIPTOR.services_by_name["Other"]
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._options = None
    _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_options = b"8\001"
    _NESTEDMESSAGE_MAPDEMOENTRY._options = None
    _NESTEDMESSAGE_MAPDEMOENTRY._serialized_options = b"8\001"
    _OTHER.methods_by_name["nested_demo"]._options = None
    _OTHER.methods_by_name[
        "nested_demo"
    ]._serialized_options = b'\212\323\344\223\002W"\024\n\022/other/nested-demo\342\001>\022</map_demo/${}/repeated_demo/$[]/$.map_demo/${}/repeated_demo'
    _DEMOMESSAGE._serialized_start = 178
    _DEMOMESSAGE._serialized_end = 213
    _SUBSUBSUBNESTEDMESSAGE._serialized_start = 215
    _SUBSUBSUBNESTEDMESSAGE._serialized_end = 299
    _SUBSUBNESTEDMESSAGE._serialized_start = 302
    _SUBSUBNESTEDMESSAGE._serialized_end = 495
    _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_start = 401
    _SUBSUBNESTEDMESSAGE_MAPDEMOENTRY._serialized_end = 495
    _SUBNESTEDMESSAGE._serialized_start = 497
    _SUBNESTEDMESSAGE._serialized_end = 583
    _NESTEDMESSAGE._serialized_start = 586
    _NESTEDMESSAGE._serialized_end = 761
    _NESTEDMESSAGE_MAPDEMOENTRY._serialized_start = 673
    _NESTEDMESSAGE_MAPDEMOENTRY._serialized_end = 761
    _OTHER._serialized_start = 764
    _OTHER._serialized_end = 945
# @@protoc_insertion_point(module_scope)
